In [70]:
import pandas as pd
import numpy as np

In [71]:
# from google.colab import drive
# drive.mount('/content/drive/')

<span style="color:green;font-weight:bold; font-size:2em">1. Import and analyse the data set.<span>

In [72]:
from keras.datasets import imdb
(X_train,Y_train),(X_test,Y_test) = imdb.load_data(num_words=10000)

<span style="color:green;font-weight:bold; font-size:2em">3. Perform following data analysis:<span>


<span style="color:red;font-weight:bold; font-size:1em"> • Print shape of features and labels
<span style="color:red;font-weight:bold; font-size:1em"> • Print value of any one feature and it's label<span>

In [73]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(25000,)
(25000,)
(25000,)
(25000,)


In [74]:
type(X_train)

numpy.ndarray

In [75]:
X_train = pd.DataFrame(X_train,index=None,columns=['Sentence'])
X_test = pd.DataFrame(X_test,columns=['Sentence'])
Y_train = pd.DataFrame(Y_train,columns=['Sentiment'])
Y_test = pd.DataFrame(Y_test,columns=['Sentiment'])

In [76]:
X = pd.concat([X_train,X_test],axis=0,ignore_index=True)
Y = pd.concat([Y_train,Y_test],axis=0,ignore_index=True)

In [77]:
print(X.shape)
print(Y.shape)

(50000, 1)
(50000, 1)


In [78]:
X.head(5)

Sentence
0  [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, ...
1  [1, 194, 1153, 194, 8255, 78, 228, 5, 6, 1463,...
2  [1, 14, 47, 8, 30, 31, 7, 4, 249, 108, 7, 4, 5...
3  [1, 4, 2, 2, 33, 2804, 4, 2040, 432, 111, 153,...
4  [1, 249, 1323, 7, 61, 113, 10, 10, 13, 1637, 1...

In [79]:
Y.head(5)

Sentiment
0          1
1          0
2          0
3          1
4          0

In [80]:
Y['Sentiment']

0        1
1        0
2        0
3        1
4        0
        ..
49995    1
49996    1
49997    0
49998    0
49999    0
Name: Sentiment, Length: 50000, dtype: int64

In [81]:
np.array(X['Sentence'][8])

array([   1,   43,  188,   46,    5,  566,  264,   51,    6,  530,  664,
         14,    9, 1713,   81,   25, 1135,   46,    7,    6,   20,  750,
         11,  141, 4299,    5,    2, 4441,  102,   28,  413,   38,  120,
       5533,   15,    4, 3974,    7, 5369,  142,  371,  318,    5,  955,
       1713,  571,    2,    2,  122,   14,    8,   72,   54,   12,   86,
        385,   46,    5,   14,   20,    9,  399,    8,   72,  150,   13,
        161,  124,    6,  155,   44,   14,  159,  170,   83,   12,    5,
         51,    6,  866,   48,   25,  842,    4, 1120,   25,  238,   79,
          4,  547,   15,   14,    9,   31,    7,  148,    2,  102,   44,
         35,  480, 3823, 2380,   19,  120,    4,  350,  228,    5,  269,
          8,   28,  178, 1314, 2347,    7,   51,    6,   87,   65,   12,
          9,  979,   21,   95,   24, 3186,  178,   11,    2,   14,    9,
         24,   15,   20,    4,   84,  376,    4,   65,   14,  127,  141,
          6,   52,  292,    7, 4751,  175,  561,   

In [82]:
Y['Sentiment'][8]

1

<span style="color:green;font-weight:bold; font-size:2em">1. Import and analyse the data set.<span>

In [83]:
count = dict()

for x in Y['Sentiment']:
    if x in count:
        count[x] +=1
    else:
        count[x] = 1
count

{1: 25000, 0: 25000}

In [84]:
print(f"The number of Positive Reviews are:     {count[1]}")
print(f"The number of Negative Reviews are:     {count[0]}")
print(f"Total number of Reviews are:            {len(Y['Sentiment'])}")

The number of Positive Reviews are:     25000
The number of Negative Reviews are:     25000
Total number of Reviews are:            50000


In [85]:
length = []
for x in X['Sentence']:
    length.append(len(x))
    
length[:5]

[218, 189, 141, 550, 147]

In [86]:
max(length)

2494

In [87]:
Y = list(Y['Sentiment'])


<span style="color:green;font-weight:bold; font-size:2em">4. Decode the feature value to get original sentence<span>

In [88]:
word_index = imdb.get_word_index()

In [89]:
print(word_index['hello'])

4822


In [90]:
vocab = dict([(value,key) for key,value in word_index.items()])

In [91]:
def tensor_to_word(sequence):
    sentence=[]
    text = ''    
    for word in sequence:
        text += vocab[word]
        text += ' '
    sentence.append(text)
    return sentence

In [92]:
translated_sentence = []
for x in X['Sentence']:
     sentence = tensor_to_word(x)
     translated_sentence.append(sentence)
     

In [93]:
translated_sentence[8]

["the out can't some to hit looking when is themselves novel as it theatre people have former some br is on dull this should rick to and thru characters one lost her show jews for of brosnan br realised back video excellent to plenty theatre involved and and off as in we no that how moments some to as on it early in we years was nothing does is 10 has as new part first that to when is possibly what have whatever of positive have 2 also of slow for as it by br though and characters has so heart broad europe film show of try making to looks in one want key bodies br when is him their that it christmas not them his dancer want this and as it his for on of great stupid of their as end should is very together br twilight us writer br were machines go bad aka were young to might us father film any more it her get predictable of alleged for find dvd from through i'm her get up happily date of lionel with other is him pushed has columbo criticized to what's of thief this so superior too not as

In [95]:
Y[8]

1

<span style="color:green;font-weight:bold; font-size:2em">2. Perform relevant sequence adding on the data<span>

In [96]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
maxlen = 20
X = pad_sequences(maxlen=maxlen, sequences=X['Sentence'], padding="post", value=0)

In [97]:
X

array([[  65,   16,   38, ...,   19,  178,   32],
       [  23,    4, 1690, ...,   16,  145,   95],
       [1352,   13,  191, ...,    7,  129,  113],
       ...,
       [ 226,   20,  272, ...,   21,  846, 5518],
       [  55,  117,  212, ..., 2302,    7,  470],
       [  19,   14,   20, ...,   34, 2005, 2643]])

<span style="color:green;font-weight:bold; font-size:2em">5. Design, train, tune and test a sequential model.<span>

In [98]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D,Bidirectional

embed_dim = 128
lstm_out = 196

model = Sequential()
model.add(Embedding(10000, embed_dim,input_length = X.shape[1]))
model.add(SpatialDropout1D(0.4))
model.add(Bidirectional(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 128)           1280000   
_________________________________________________________________
spatial_dropout1d_1 (Spatial (None, 20, 128)           0         
_________________________________________________________________
bidirectional_1 (Bidirection (None, 392)               509600    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 393       
Total params: 1,789,993
Trainable params: 1,789,993
Non-trainable params: 0
_________________________________________________________________
None


In [99]:
X

array([[  65,   16,   38, ...,   19,  178,   32],
       [  23,    4, 1690, ...,   16,  145,   95],
       [1352,   13,  191, ...,    7,  129,  113],
       ...,
       [ 226,   20,  272, ...,   21,  846, 5518],
       [  55,  117,  212, ..., 2302,    7,  470],
       [  19,   14,   20, ...,   34, 2005, 2643]])

In [100]:
X.shape

(50000, 20)

In [101]:
from sklearn.model_selection import train_test_split

Y=np.array(Y)
X_train, x_test, Y_train, y_test = train_test_split(X,Y, test_size = 0.30, random_state = 42)
print(X_train.shape,len(Y_train))
print(x_test.shape,len(y_test))

(35000, 20) 35000
(15000, 20) 15000


In [102]:
x_test[5]

array([ 713,  920,  924,  108,  920,  924, 7039,  321,  108,   40,    2,
       1536, 4644,  525,   73,  224,  401,   98,    2,   46])

In [103]:
y_test[5]

1

In [105]:
batch_size = 500
model.fit(X_train, Y_train, epochs = 10, batch_size=batch_size, verbose = 1)

Train on 35000 samples
Epoch 1/10
35000/35000 [==============================] - 45s 1ms/sample - loss: 0.3804 - accuracy: 0.8288
Epoch 2/10
35000/35000 [==============================] - 41s 1ms/sample - loss: 0.3627 - accuracy: 0.8375
Epoch 3/10
35000/35000 [==============================] - 41s 1ms/sample - loss: 0.3483 - accuracy: 0.8448
Epoch 4/10
35000/35000 [==============================] - 42s 1ms/sample - loss: 0.3321 - accuracy: 0.8531
Epoch 5/10
35000/35000 [==============================] - 42s 1ms/sample - loss: 0.3167 - accuracy: 0.8605
Epoch 6/10
35000/35000 [==============================] - 43s 1ms/sample - loss: 0.2986 - accuracy: 0.8727
Epoch 7/10
35000/35000 [==============================] - 44s 1ms/sample - loss: 0.2810 - accuracy: 0.8805
Epoch 8/10
35000/35000 [==============================] - 45s 1ms/sample - loss: 0.2610 - accuracy: 0.8890
Epoch 9/10
35000/35000 [==============================] - 44s 1ms/sample - loss: 0.2423 - accuracy: 0.8995
Epoch 10/10
35

In [106]:
score,acc = model.evaluate(x_test, y_test, verbose = 2, batch_size = batch_size)
print("score: %.2f" % (score))
print("acc: %.2f" % (acc))

15000/1 - 7s - loss: 0.6303 - accuracy: 0.7666
score: 0.60
acc: 0.77


<span style="color:green;font-weight:bold; font-size:2em">6. Use the designed model to print the prediction on any one sample.<span>

In [107]:
y = model.predict(np.expand_dims(x_test[5],axis=0))
y[0]

array([0.8858513], dtype=float32)

In [108]:
y_test[5]

1